import Link from "next/link";
import BikeMatrixCore from "../components/BikeMatrixCore";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container flex items-center w-full mx-auto my-4 space-x-8">
          <Link href="/">Home</Link>
          <Link href="/collection">Collection</Link>
          <Link href="/product">Product</Link>

          {/* Bike Selector Button (id="bm_selectBikeButton") */}
          <button
            id="bm_selectBikeButton"
            className="p-2 !ml-auto border rounded-md w-14 h-14 bm-header-btn bm-icon bm-bike-select-icon"
            style={{ backgroundColor: "#ffffff", color: "#000000" }}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 48 48"
              className="w-full h-full"
            >
              <path
                fill="currentColor"
                fillRule="evenodd"
                d="m35.745 12.17l-4.925 1.48l3.28 8.578a8 8 0 1 1-1.868.715l-1.648-4.31l-5.682 11.802A1 1 0 0 1 24 31h-4.062A8.001 8.001 0 0 1 4 30a8 8 0 0 1 15.938-1h2.5l-4.88-13.664A.998.998 0 0 1 17.5 15H16a1 1 0 1 1 0-2h4.5a1 1 0 1 1 0 2h-.938l1.842 5.157l8.127-4.277l-.965-2.523a1 1 0 0 1 .647-1.315l5.957-1.787l.575 1.915Zm-13.662 9.89l1.972 5.52l4.23-8.784l-6.202 3.264Zm12.983 8.297l-2.113-5.527a6 6 0 1 0 1.868-.715l2.113 5.528a1 1 0 0 1-1.868.714ZM17.917 29H12a1 1 0 1 0 0 2h5.917A6.002 6.002 0 0 1 6 30a6 6 0 0 1 11.917-1Z"
                clipRule="evenodd"
              ></path>
            </svg>
          </button>
        </div>

        {/* Bike Matrix Web Component - Bike Selector */}
        <bikematrix-bikeselector></bikematrix-bikeselector>

        {/* Bike Matrix Config - Bike Selector */}
        <script type="application/json" data-bikematrix-config>
          {`
          {
            "logLevel": "verbose",
            "apiUrl": "https://bikematrix-20230522-1515-dev-apim.azure-api.net/proxy/v3/",
            "pageType": "collection",
            "collections": [
              {
                "title": "Brake pads",
                "handle": "brake-pads",
                "url": "/collections/brake-pads"
              },
              { 
                "title": "Tyres & Tubes",
                "handle": "tyres-tubes",
                "url": "/collections/tyres-tubes"
              },
              {
                "title": "Rotors",
                "handle": "rotors-1",
                "url": "/collections/rotors-1"
              },
              {
                "title": "Wheels & Rims",
                "handle": "wheels-rims",
                "url": "/collections/wheels-rims"
              }
            ],
            "categories": [
              {
                "title": "Brake Pads",
                "text_id": "category_brakepads",
                "collection": "Brake pads"
              }
            ],
          }`}
        </script>

        {children}

        <BikeMatrixCore />
      </body>
    </html>
  );
}
