import Link from "next/link";
import BikeMatrixCore from "../components/BikeMatrixCore";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container flex items-center w-full mx-auto my-4 space-x-8">
          <Link href="/">Home</Link>
          <Link href="/collection">Collection</Link>
          <Link href="/product">Product</Link>

          {/* Bike Selector Button (id="bm_selectBikeButton") */}
          <div className="!ml-auto">
            <bikematrix-bikon data-color="#000"></bikematrix-bikon>
          </div>
        </div>

        {/* Bike Matrix Web Component - Bike Selector */}
        <bikematrix-bikeselector></bikematrix-bikeselector>
        <bikematrix-bikeselectorbanner
          data-title="Bike Selector Banner"
          data-color="#000000"
          data-full-width="false"
          data-font-color="#ffffff"
          data-show="true"
        ></bikematrix-bikeselectorbanner>
        {/* Bike Matrix Config - Bike Selector */}
        <script type="application/json" data-bikematrix-config>
          {`
          {
            "logLevel": "verbose",
            "apiUrl": "https://api-staging.bikematrix.io/bike/v2/",
            "apiKey": "YOUR_API_KEY",
            "pageType": "collection",
            "collections": [
              {
                "title": "Brake pads",
                "handle": "brake-pads",
                "url": "/collections/brake-pads"
              },
              { 
                "title": "Tyres & Tubes",
                "handle": "tyres-tubes",
                "url": "/collections/tyres-tubes"
              },
              {
                "title": "Rotors",
                "handle": "rotors-1",
                "url": "/collections/rotors-1"
              },
              {
                "title": "Wheels & Rims",
                "handle": "wheels-rims",
                "url": "/collections/wheels-rims"
              }
            ],
            "categories": [
              {
                "title": "Brake Pads",
                "text_id": "category_brakepads",
                "collection": "Brake pads"
              }
            ],
            "virtualWorkshop": false
          }`}
        </script>

        {children}

        <BikeMatrixCore />
      </body>
    </html>
  );
}
